### PR TITLE
EffectsProcessorDemo in Swift initial commit

### PR DESCRIPTION
**Pull request by codeclips**
Demo 99% completed. Effects work for Loops.
ToDo: SongViewController.swift - Not saving "exported.wav". Looking for assistance.

### CODE REVIEW

**Comment by aure** [comment]
Cool!  I'll merge and have a look at the exported.wav issue.

**Comment by aure** [comment]
That should do it!

**Comment by codeclips** [comment]
You're the man, Aure!

**Comment by narner** [comment]
This is great, thanks again for your contributions @codeclips!

**Pull request merged**
